version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.12.1
    - 5.12.3
    - 5.12.5
- package-ecosystem: docker
  directory: "/mongo-seed"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 99
